# Generated by Django 3.2 on 2022-03-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='other_email',
            field=models.EmailField(blank=True, default='null', max_length=254, null=True),
        ),
    ]
