# Generated by Django 3.2 on 2022-02-21 15:51

from django.db import migrations, models
import user.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220221_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.users',),
            managers=[
                ('objects', user.managers.CustomUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='phone_number_verified',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='users',
            name='verification',
            field=models.CharField(choices=[('Phone', 'Phone Number'), ('Email', 'Email')], default='', max_length=100),
        ),
    ]
