# Generated by Django 3.2 on 2022-03-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_contact_other_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='birth_date1',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number1',
            new_name='phone_number',
        ),
    ]
