# Generated by Django 3.2 on 2022-03-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220312_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='contact',
            name='other_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('owner', 'email')},
        ),
    ]
