# Generated by Django 3.2 on 2022-03-12 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220312_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_email', to=settings.AUTH_USER_MODEL),
        ),
    ]
