# Generated by Django 3.2 on 2022-02-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220221_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
