# Generated by Django 3.2 on 2022-03-24 14:50

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that Phone number already exists.'}, help_text='Example : 09125573688', max_length=11, null=True, unique=True, validators=[user.models.MobileNumberValidator()], verbose_name='Phone Number'),
        ),
    ]
