# Generated by Django 3.2 on 2022-03-26 13:44

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220324_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(default=None, error_messages={'unique': 'A user with that Phone number already exists.'}, help_text='Example : 09125573688', max_length=11, unique=True, validators=[user.models.MobileNumberValidator()], verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
