# Generated by Django 3.2 on 2022-02-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_coderegister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coderegister',
            name='user',
        ),
        migrations.AddField(
            model_name='coderegister',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
    ]
