# Generated by Django 3.2 on 2022-03-03 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220303_1429'),
        ('user', '0009_alter_users_verification'),
    ]

    operations = [
    ]
