# Generated by Django 3.2 on 2022-02-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_users_verification'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
