# Generated by Django 3.2 on 2022-02-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_users_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='users',
            name='verification',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email')], default='', max_length=100),
        ),
    ]
