# Generated by Django 3.2 on 2022-03-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220303_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='other_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
