# Generated by Django 3.2 on 2022-03-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_contact_other_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='other_email',
            field=models.CharField(blank=True, default='default@mail.com', max_length=500, null=True),
        ),
    ]
