# Generated by Django 3.2 on 2022-03-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_contact_other_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='other_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
