# Generated by Django 3.2 on 2022-03-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_contact_other_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='other_email',
            field=models.EmailField(blank=True, default='default@mail.com', max_length=254, null=True),
        ),
    ]
