# Generated by Django 3.2 on 2022-03-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UpdateEmailOfUser',
        ),
    ]
