# Generated by Django 3.2 on 2022-03-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20220312_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('recipients', 'recipients'), ('cc', 'cc'), ('bcc', 'bcc')], default='', max_length=10),
        ),
    ]
