# Generated by Django 3.2 on 2022-02-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20220224_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='mail',
            new_name='category',
        ),
    ]
