# Generated by Django 3.2 on 2022-02-25 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0005_rename_mail_email_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_drafted',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_starred',
        ),
        migrations.RemoveField(
            model_name='email',
            name='recipients',
        ),
        migrations.AddField(
            model_name='email',
            name='bcc',
            field=models.ManyToManyField(related_name='bcc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='cc',
            field=models.ManyToManyField(related_name='cc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='email',
            name='to',
            field=models.ManyToManyField(related_name='to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='mail.Category'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
