# Generated by Django 3.2 on 2022-03-23 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0005_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='text_include',
        ),
        migrations.AddField(
            model_name='filter',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_user', to=settings.AUTH_USER_MODEL, verbose_name='from'),
        ),
    ]
