# Generated by Django 3.2 on 2022-03-03 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0007_auto_20220301_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='bcc',
            field=models.ManyToManyField(blank=True, related_name='bcc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categories', to='mail.Category'),
        ),
        migrations.AlterField(
            model_name='email',
            name='cc',
            field=models.ManyToManyField(blank=True, related_name='cc', to=settings.AUTH_USER_MODEL),
        ),
    ]
