# Generated by Django 3.2 on 2022-03-06 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_auto_20220303_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mail.email'),
        ),
    ]
