# Generated by Django 3.2 on 2022-03-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_auto_20220329_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='trash_or_archive',
            field=models.CharField(blank=True, choices=[('Trash', 'Trash'), ('Archive', 'Archive')], max_length=10, null=True),
        ),
    ]
