# Generated by Django 3.2 on 2022-03-06 21:28

from django.db import migrations, models
import mail.models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_email_reply_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterField(
            model_name='email',
            name='file',
            field=models.FileField(blank=True, help_text='max 25 megabytes', null=True, upload_to=mail.models.user_directory_path, validators=[mail.models.file_validator]),
        ),
    ]
