# Generated by Django 3.2 on 2022-03-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_filter_trash_or_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='filter_both',
        ),
        migrations.AlterField(
            model_name='filter',
            name='from_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
