# Generated by Django 3.2 on 2022-03-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_auto_20220307_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='signature_image',
        ),
    ]
