# Generated by Django 3.2 on 2022-03-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_auto_20220330_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('recipients', 'recipients'), ('cc', 'cc'), ('bcc', 'bcc'), ('total', 'total')], default='', max_length=10),
        ),
    ]
