# Generated by Django 3.2 on 2022-03-09 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0014_alter_category_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateEmailOfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Archive', 'Archive'), ('Trash', 'Trash'), ('Read', 'Read')], max_length=10)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email', to='mail.email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
