# Generated by Django 3.2 on 2022-03-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0015_updateemailofuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_trashed',
        ),
        migrations.RemoveField(
            model_name='updateemailofuser',
            name='status',
        ),
        migrations.AddField(
            model_name='updateemailofuser',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updateemailofuser',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updateemailofuser',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
